travis:
  secure:
    BINSTAR_TOKEN: i0MLX7NahxeDU98EcspYbB/fuJK2mX9P4u+XkDJEI+ZYt7AV85mmguR2PLfZwufhDsGBR4DnaSDFzN8gf/0jo1BRQ63GdAi1KrAEzHVkEvGt7maYesfmzfyfXAY2vDV3HTXpeaJw2x0LXqrITKEV/pxVeuir5xqOTu2CLNgzQlveziFqnrjUycf6FVFfvtD0bg8WmM6xl3g8yLj2Ys370hwIOyC6EpdAsBGBFkIKoBmnAvEdSDmcYAAKLcSrS1JdNXq/I/aEebOW6OThnfhcch0i2P0xIhd6IyFjH3JXp3DpFQyI6uk7J+VyySUIFsGor5/lI//4Exknok6PQ/EqsHf5WdtiStuTGJ9B2piZyDn//ZpZaXqsDx5sd5KIK3iAVZLveuphyqW7V2ZjygK+TFFRpy6zlHs/UfkAIRIq1jpI+doHHBIrWxzgFtgu5ZgF4NY4bl2m5wHZolctmgQK4NB0DEJCOLTcTsyOfvxi6uvPXxT/QyfFozw40+rJZ77jqpeMemaTMygp/zWIDHc0RNFqWJaXD/2pRYQVQWm5zMfQu0NKTmEwoaTU9QUa1SsxA6jlsEtCHzoZ7ox0u+fkCxUXSvjGfr8akDmMkANCXHX0YCcMENnJPMhFLjpWTq/kZ+ud0h2kDEuVwN2FXITDDrdnpyFKjXfw5qg9HFrsPR8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
